# Generated by Django 3.0 on 2022-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='file',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
