# Generated by Django 3.0 on 2022-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_group_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='Полное имя')),
                ('topic', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('typescript', 'Typescript'), ('golang', 'Golang'), ('sql', 'Sql'), ('swift', 'Swift'), ('perl', 'Perl')], default='java', max_length=50, verbose_name='Предмет')),
                ('students', models.ManyToManyField(to='proj.Student')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ('topic',),
            },
        ),
    ]
