# Generated by Django 3.0 on 2022-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='full_name',
            field=models.CharField(max_length=40, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='topic',
            field=models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('golang', 'Golang'), ('typescript', 'Typescript'), ('swift', 'Swift'), ('php', 'PHP'), ('matlab', 'MatLab'), ('sql', 'SQL'), ('ruby', 'Ruby'), ('delphi', 'Delphi')], default='java', max_length=30, verbose_name='Предмет'),
        ),
    ]
