# Generated by Django 3.0 on 2022-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_auto_20220211_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
