# Generated by Django 4.0.3 on 2022-03-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_alter_student_account_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время обновления')),
                ('title', models.CharField(max_length=35)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Файл ДЗ',
                'verbose_name_plural': 'Файлы ДЗ',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время обновления')),
                ('title', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=35)),
                ('logo', models.ImageField(upload_to='')),
                ('is_checked', models.BooleanField(default=False)),
                ('homework_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.file')),
                ('student_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='proj.student')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ('title', 'subject', 'student_name'),
            },
        ),
    ]
